import {
  oblykBalance,
  oblykClamp,
  oblykClimbingStyleBoulder,
  oblykClimbingStyleCoordination,
  oblykClimbingStyleEndurance,
  oblykClimbingStyleFinger,
  oblykClimbingStyleGrip,
  oblykClimbingStylePhysics,
  oblykClimbingStyleResistance,
  oblykClimbingStyleSmallPeople,
  oblykClimbingStyleTallPeople,
  oblykClimbingStyleTechnical,
  oblykCommitment,
  oblykComplex,
  oblykCoreStrength,
  oblykDynamic,
  oblykPrecision,
  oblykPromptness,
  oblykSensation,
  oblykU8,
  oblykU10,
  oblykU12,
  oblykU14,
  oblykU16,
  oblykU18,
  oblykVolume,
} from '@/assets/oblyk-icons/index.js'

export const ClimbingStyleIcons = {
  boulder: oblykClimbingStyleBoulder,
  endurance: oblykClimbingStyleEndurance,
  resistance: oblykClimbingStyleResistance,
  technical: oblykClimbingStyleTechnical,
  physics: oblykClimbingStylePhysics,
  finger: oblykClimbingStyleFinger,
  grip: oblykClimbingStyleGrip,
  coordination: oblykClimbingStyleCoordination,
  tall_people: oblykClimbingStyleTallPeople,
  small_people: oblykClimbingStyleSmallPeople,
  balance: oblykBalance,
  clamp: oblykClamp,
  volume: oblykVolume,
  core_strength: oblykCoreStrength,
  commitment: oblykCommitment,
  precision: oblykPrecision,
  promptness: oblykPromptness,
  dynamic: oblykDynamic,
  complex: oblykComplex,
  sensation: oblykSensation,
  u8: oblykU8,
  u10: oblykU10,
  u12: oblykU12,
  u14: oblykU14,
  u16: oblykU16,
  u18: oblykU18,
}
